dist: bionic

language: python

python:
  - 3.6
  - 3.7
  - 3.8
#  - 3.9-dev

install:
  - pip install pipenv
  - pipenv install --dev

git:
  depth: 3

branches:       # since the master branch is the only one where PRs are
  only:         # merged in.
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/    # for release tags

script:
  - pipenv run pytest
  - pipenv run mypy ./ || true
  - cat test.log

# TODO deploy

after_success:
  - codecov
